"""Replays a golden scenario (tests/golden/scenarios.json) through the Python CLI.

The scenario file and the expected bytes were generated by TypeScript stage 1; this runner is the
Python half of the cross-language parity gate (docs/design/v1-python.md §5).
"""

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from falcon_axi.cli import run
from falcon_axi.cursor import CursorContext, encode_cursor
from falcon_axi.transport.operations import operation, path_arguments
from falcon_axi.transport.types import FalconResponse, RequestArgs
from tests.support.recorded import CREDENTIAL_ENV, NO_CREDENTIAL_ENV, Responder, as_response, fixture

GOLDEN = Path(__file__).resolve().parent.parent / "golden"


def scenarios() -> list[dict[str, Any]]:
    spec = json.loads((GOLDEN / "scenarios.json").read_text(encoding="utf-8"))
    return list(spec["scenarios"])


def exit_codes() -> dict[str, int]:
    return dict(json.loads((GOLDEN / "exit-codes.json").read_text(encoding="utf-8")))


def expected_stdout(name: str) -> str:
    return (GOLDEN / f"{name}.txt").read_text(encoding="utf-8")


def _generated(spec: Mapping[str, Any], args: RequestArgs) -> FalconResponse:
    if spec["kind"] == "ids":
        resources = [f"ldt:synthetic-agent-{index}:{index}" for index in range(spec["count"])]
        total = spec.get("total")
        meta = {} if total is None else {"meta": {"pagination": {"total": total}}}
        return FalconResponse(status=200, headers={}, body={**meta, "resources": resources})
    ids = list(args.body["composite_ids"])
    taken = ids if spec.get("take") is None else ids[: spec["take"]]
    ordered = list(reversed(taken)) if spec.get("reverse") else taken
    return FalconResponse(
        status=200,
        headers={},
        body={
            "resources": [
                {
                    "composite_id": id,
                    "severity_name": spec["severity_name"],
                    "tactic": spec["tactic"],
                    "device": {"hostname": spec["hostname"]},
                }
                for id in ordered
            ]
        },
    )


def _responder_for(entry: Mapping[str, Any]) -> Responder:
    answer = None
    if entry.get("fixture"):
        answer = fixture(entry["fixture"])
    elif entry.get("response"):
        answer = as_response(entry["response"])

    def responder(id: str, args: RequestArgs) -> FalconResponse | None:
        if id != entry["op"]:
            return None
        return _generated(entry["generate"], args) if entry.get("generate") else answer

    return responder


class _GoldenTransport:
    def __init__(self, responders: list[Responder], oauth: list[FalconResponse]) -> None:
        self.responders = responders
        self.oauth = oauth

    def request(self, id: str, args: RequestArgs) -> FalconResponse:
        path_arguments(operation(id), dict(args.path_params or {}))
        for responder in self.responders:
            answer = responder(id, args)
            if answer is not None:
                return answer
        raise AssertionError(f"no recorded response for {id}")

    def request_oauth_token(self, args: Any) -> FalconResponse:
        return self.oauth.pop(0) if len(self.oauth) > 1 else self.oauth[0]


def replay(scenario: Mapping[str, Any]) -> tuple[str, int]:
    env = dict(NO_CREDENTIAL_ENV) if scenario.get("env") == "none" else {**CREDENTIAL_ENV, **scenario.get("envExtra", {})}
    responders = [_responder_for(entry) for entry in scenario.get("responders", [])]
    oauth = (
        [fixture(entry["fixture"]) if entry.get("fixture") else as_response(entry["response"]) for entry in scenario["oauth"]]
        if scenario.get("oauth")
        else [fixture("oauth2/token-success.json")]
    )
    argv = list(scenario["argv"])
    if scenario.get("cursor"):
        context = CursorContext(
            operation="GetQueriesAlertsV2",
            client_id=CREDENTIAL_ENV["FALCON_CLIENT_ID"],
            origin="https://api.crowdstrike.com",
        )
        argv += ["--cursor", encode_cursor(scenario["cursor"]["position"], context, CREDENTIAL_ENV["FALCON_CLIENT_SECRET"])]
    # The home view prints argv[0]; both runners pin it so the golden text is portable.
    return run(argv, _GoldenTransport(responders, oauth), env, bin="falcon-axi")
